import type { AppState, ActionStep } from '../../types.js';
import type { Store } from '../../state/store.js';

export function mountAgentPanel(el: HTMLElement, store: Store<AppState>): void {
  el.innerHTML = `
    <div class="panel-header" title="§4.1 Agent — The RL agent that interacts with the environment. Uses retrieved memories as context to inform actions. Actions: go_to, examine, take, use, combine, give.">Agent</div>
    <div class="panel-body" id="agent-body">
      <div class="empty-state">Agent will act when a task is running.</div>
    </div>
  `;

  const body = el.querySelector('#agent-body')! as HTMLElement;

  store.on('game', (game) => {
    if (game.phase === 'idle' || !game.currentTask) {
      body.innerHTML = '<div class="empty-state">Agent will act when a task is running.</div>';
      return;
    }
    renderAgent(body, game.steps, game.reward, game.phase, game.agentPromptPreview);
  });
}

function renderAgent(
  body: HTMLElement,
  steps: ActionStep[],
  reward: number | null,
  phase: string,
  promptPreview: string,
): void {
  body.innerHTML = '';

  // Phase indicator
  const phaseEl = document.createElement('div');
  phaseEl.style.cssText = 'font-size: 13px; color: var(--text-secondary); margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px;';
  phaseEl.textContent = `Phase: ${phase.replace(/_/g, ' ')}`;
  phaseEl.title = 'Current phase of the MemRL loop: retrieval → agent_acting → dm_responding → q_update → memory_creation.';
  body.appendChild(phaseEl);

  // Reward display (when task is complete)
  if (reward !== null) {
    const rewardEl = document.createElement('div');
    rewardEl.className = 'reward-display';
    rewardEl.title = `§3.5 — Binary reward signal: SuccessReward(r⁺) for task success, FailureReward(r⁻) for failure. This reward drives the Q-value update (Eq. 8) for all memories that were in context.`;
    rewardEl.innerHTML = `
      <span class="label">Task Reward</span>
      <span class="value ${reward > 0 ? 'positive' : 'negative'}" style="font-size: 20px; font-weight: 700;">
        ${reward > 0 ? '+' : ''}${reward.toFixed(1)}
      </span>
    `;
    body.appendChild(rewardEl);
  }

  // Steps (most recent first)
  if (steps.length > 0) {
    const label = document.createElement('div');
    label.className = 'section-label';
    label.style.marginTop = '12px';
    label.textContent = 'Agent Actions';
    label.title = 'Chronological log of the agent\'s chain-of-thought reasoning and selected actions. The agent sees the task description, world state, and retrieved memory context but NOT the DM\'s scratch buffer or success conditions.';
    body.appendChild(label);

    const reversed = [...steps].reverse();
    for (const step of reversed) {
      // Thinking
      if (step.agentDecision.thinking) {
        const thinking = document.createElement('div');
        thinking.className = 'agent-thinking';
        thinking.textContent = step.agentDecision.thinking;
        thinking.title = 'The agent\'s internal chain-of-thought reasoning before selecting an action. This is generated by the LLM but not shown to the DM.';
        body.appendChild(thinking);
      }

      // Action
      const action = document.createElement('div');
      action.className = 'agent-action';
      const actionStr = formatAction(step.agentDecision.action);
      action.innerHTML = `<span style="color: var(--text-secondary); font-size: 12px; font-weight: 400;">Step ${step.stepNumber}</span> ${escapeHtml(actionStr)}`;
      action.title = 'The parsed action sent to the DM. Available actions: go_to(location), examine(object), take(object), use(object), combine(obj1, obj2), give(item, target).';
      body.appendChild(action);

      // DM Response
      const dm = document.createElement('div');
      dm.className = 'narrative-entry dm';
      dm.textContent = step.dmResponse.narrative;
      dm.title = 'The DM\'s narrative response — generated in Pass 2 of the two-pass tick after the DM has internally evaluated the action against world axioms and updated the scratch buffer.';
      body.appendChild(dm);

      // Status badge
      if (step.dmResponse.status !== 'continue') {
        const badge = document.createElement('span');
        badge.className = `badge ${step.dmResponse.status === 'success' ? 'success' : 'failure'}`;
        badge.textContent = step.dmResponse.status.toUpperCase();
        badge.style.marginBottom = '8px';
        badge.style.display = 'inline-block';
        badge.title = step.dmResponse.status === 'success'
          ? 'All success conditions in the DM\'s task contract are satisfied. The agent receives SuccessReward(r⁺).'
          : 'Task failed — either the agent exceeded MaxStepsPerTask or the DM determined the task is no longer achievable. The agent receives FailureReward(r⁻).';
        body.appendChild(badge);
      }
    }
  }

  // Prompt preview (collapsible)
  if (promptPreview) {
    const details = document.createElement('details');
    details.style.marginTop = '12px';
    const summary = document.createElement('summary');
    summary.className = 'section-label';
    summary.style.cursor = 'pointer';
    summary.textContent = 'Full Agent Prompt';
    summary.title = '§3.3 — The complete prompt sent to the agent LLM. Includes the system prompt, task description, world state, and the k₂ retrieved memory experiences injected as context.';
    details.appendChild(summary);

    const pre = document.createElement('div');
    pre.className = 'context-preview';
    pre.textContent = promptPreview;
    details.appendChild(pre);

    body.appendChild(details);
  }
}

function formatAction(action: { type: string; target: string; secondTarget?: string }): string {
  if (action.secondTarget) return `${action.type}(${action.target}, ${action.secondTarget})`;
  return `${action.type}(${action.target})`;
}

function escapeHtml(str: string): string {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}
